version: '3'

services:
  front:
    build: ./front
    ports:
      - 3031
    volumes:
      - ./front:/app:cached

  router:
    build: ./router
    depends_on:
      - front
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/web

  unit-tests:
    build: ./front
    volumes:
      - ./front:/app:cached
    command: [python, '-m', 'pytest', '../tests/']
